# Generated by Django 4.2 on 2024-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(default='https://www.youtube.com/watch?v=C8YtdC8mxTU', unique=True),
            preserve_default=False,
        ),
    ]
