# Generated by Django 4.2 on 2024-01-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
            preserve_default=False,
        ),
    ]
